In [1]:
import sqlite3
import cleaning
import database
import numpy as np
import pandas as pd
import integration

In [2]:
results = integration.integrate_trr()

/Users/qingweilan/Desktop/dev/ai339/ai339-project/data-cleaning/integration.py:168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remaining['officer_id'] = 'NULL'
/Users/qingweilan/Desktop/dev/ai339/ai339-project/data-cleaning/integration.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results['officer_unit_detail_id'] = pd.to_numeric(results['officer_unit_detail_id'])

In [3]:
results

,id,crid,event_id,beat,block,direction,street,location,trr_datetime,indoor_or_outdoor,...,subject_injured,subject_alleged_injury,subject_age,subject_birth_year,subject_gender,subject_race,officer_id,officer_unit_id,officer_unit_detail_id,point
0,1165515,NULL,10873,111,2XX,N,Wabash Ave,Sidewalk,2019-04-17 04:59:00 PM,Outdoor,...,False,False,39,1980,M,WHITE,34153,2,1,0101000020E61000001940530A15E855C05DFE9EB360F1...
1,2192334,NULL,3180,2533,16XX,N,Leclaire Ave,Sidewalk,2019-07-02 07:09:00 AM,Outdoor,...,False,False,36,1983,M,BLACK,34195,26,25,0101000020E6100000C048C3842CF055C078A686EC72F4...
2,5909387,NULL,9201,1231,17XX,W,Taylor St,Hospital Building/Grounds,2020-04-29 04:50:00 PM,Outdoor,...,False,False,54,1966,M,BLACK,34234,12,11,0101000020E6100000B90DB44CD0EA55C04910AE8042EF...
3,5776976,NULL,2009603012,411,82XX,S,Woodlawn Ave,Sidewalk,2020-04-05 08:30:00 AM,Outdoor,...,False,False,54,1966,M,BLACK,34205,5,4,0101000020E610000076A911FA19E655C04BC741AE79DF...
4,5914654,NULL,2012109746,712,56XX,S,Morgan St,Vacant Lot/Land,2020-04-30 06:03:00 PM,Outdoor,...,False,False,29,1991,M,BLACK,34353,8,7,0101000020E61000001AC231CB9EE955C023F59ECA69E5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17487,761110,None,7558,1634,50XX,W,Warwick Ave,Alley,2018-12-12 12:20:00 PM,Outdoor,...,False,False,45,1973,M,HISPANIC,NULL,26,25,0101000020E61000002E8D5F7825F055C06FFF80BD78F9...
17488,833879,None,1434,2515,55XX,W,Grand Ave,Jail / Lock-Up Facility,2019-01-19 02:30:00 AM,Indoor,...,False,False,28,1991,M,HISPANIC,NULL,26,25,0101000020E610000067327788DAF055C04814FF1C8BF5...
17489,962145,None,8014,822,53XX,S,St Louis Ave,Sidewalk,2019-03-11 01:40:00 PM,Outdoor,...,False,False,19,2000,M,HISPANIC,NULL,26,25,0101000020E6100000A0AC736781ED55C0DF162CD505E6...
17490,1576357,None,11892,2515,55XX,W,Grand Ave,Jail / Lock-Up Facility,2019-05-20 10:10:00 PM,Indoor,...,False,False,30,1989,M,HISPANIC,NULL,26,25,0101000020E610000067327788DAF055C04814FF1C8BF5...
17491,5004859,None,14924,1414,25XX,N,Milwaukee Ave,Vehicle Non-Commercial,2020-01-21 08:32:00 PM,Outdoor,...,False,False,24,1996,M,HISPANIC,NULL,26,25,0101000020E610000072EF2B20FEEC55C0950D6B2A8BF6...

In [4]:
trr = database.download('trr_trr_refresh')

In [9]:
trr

,id,event_number,cr_number,beat,block,direction,street,location,trr_datetime,indoor_or_outdoor,...,officer_race,officer_age,officer_appointed_date,officer_birth_year,officer_unit_name,officer_unit_detail,trr_created,latitude,longitude,point
0,96630,1611411724,None,1124,30XX,West,JACKSON BLVD,STREET,2016-04-23 18:18:00-05,None,...,WHITE,30,02-18-14,None,11,None,None,41.8776497,-87.7012653,0101000020E61000007554DA87E1EC55C00F6C4BD356F0...
1,97999,1618611539,None,723,9XX,West,MARQUETTE RD,STREET,2016-07-04 17:06:00-05,Outdoor,...,WHITE,30,11-25-13,None,7,None,None,41.7724444,-87.6470302,0101000020E61000008F215BF168E955C03AFD4575DFE2...
2,98796,1623610044,None,811,53XX,South,NARRAGANSETT AVE,RESIDENCE,2016-08-23 16:14:00-05,Outdoor,...,WHITE,51,09-30-02,None,8,None,None,41.7959057,-87.7821939,0101000020E61000005DE800770FF255C09919EC3CE0E5...
3,99293,1626900073,None,2232,100XX,South,EMERALD AVE,SIDEWALK,2016-09-25 20:00:00-05,None,...,WHITE,34,12-16-09,None,22,None,None,41.7122367,-87.6421715,0101000020E610000017BB7D5619E955C067C17A922ADB...
4,99369,1627409687,None,634,XX,West,95TH ST,SIDEWALK,2016-09-30 17:13:00-05,None,...,BLACK,46,02-21-06,None,6,None,None,41.72199,-87.626064,0101000020E6100000FD4CBD6E11E855C0FF04172B6ADC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17460,6043642,262,None,2534,12XX,N,KILDARE AVE,RESIDENCE - PORCH / HALLWAY,2020-05-26 00:30:00-05,INDOOR,...,HISPANIC,-25,2019-FEB-19,1995,25,None,2020-05-26 03:42:00-05,41.9027893,-87.733746,0101000020E61000008864C8B1F5EE55C0E1568B998EF3...
17461,6043651,262,None,2534,12XX,N,KILDARE AVE,RESIDENCE - PORCH / HALLWAY,2020-05-26 00:30:00-05,INDOOR,...,HISPANIC,-24,2019-AUG-16,1996,25,None,2020-05-26 03:45:00-05,41.9027893,-87.733746,0101000020E61000008864C8B1F5EE55C0E1568B998EF3...
17462,6059341,2014902656,None,1023,26XX,W,21ST ST,APARTMENT,2020-05-28 05:20:00-05,INDOOR,...,HISPANIC,-31,2017-SEP-18,1989,10,None,2020-05-28 06:52:00-05,41.8540554,-87.6908109,0101000020E61000001ACEEB3E36EC55C071FCF5AF51ED...
17463,6059467,2014902656,None,1023,26XX,W,21ST ST,APARTMENT,2020-05-28 05:20:00-05,INDOOR,...,HISPANIC,-26,2018-NOV-27,1994,10,None,2020-05-28 07:24:00-05,41.8540554,-87.6908109,0101000020E61000001ACEEB3E36EC55C071FCF5AF51ED...
17464,6059839,2014902656,None,1023,26XX,W,21ST ST,APARTMENT,2020-05-28 05:20:00-05,INDOOR,...,HISPANIC,-36,2017-SEP-18,1984,10,None,2020-05-28 08:29:00-05,41.8540554,-87.6908109,0101000020E61000001ACEEB3E36EC55C071FCF5AF51ED...